version: '3'

services:
  api:
    build: .
    container_name: "phoenix_api_boilerplate"
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    links:
      - postgres
      - rabbitmq
    command: ["mix", "phx.server"]
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: phoenix_api_boilerplate_dev
      PGPORT: 5432
      PGHOST: postgres
  postgres:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.8.2-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
